import type {
  PaletteMeta,
  PortfolioBuilderState,
  TemplateMeta,
  TypographyMeta,
} from './builderTypes';

export const BUILDER_STEPS = ['template', 'palette', 'typography', 'content', 'socials', 'review'] as const;

export const PORTFOLIO_TEMPLATES: TemplateMeta[] = [
  {
    id: 'creative_bold',
    name: 'Alex Rivera - Creative Portfolio',
    category: 'creative',
    description: 'Exact premium portfolio style: hero, stats, about, expertise, projects, timeline, testimonials, and contact.',
    previewImage: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'tech_developer',
    name: 'Kenji Takeda - Samurai Developer',
    category: 'technical',
    description: 'Ink-inspired editorial portfolio with philosophy cards, mastery sections, case studies, journey timeline, and contact.',
    previewImage: 'https://images.unsplash.com/photo-1460891053196-b9d4d9483d9b?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'modern_gradient',
    name: 'Nova Chen - Neon Architect',
    category: 'modern',
    description: 'Cyberpunk neon portfolio with glowing hero, grid background, tech services, project matrix, timeline, and high-contrast contact.',
    previewImage: 'https://images.unsplash.com/photo-1518773553398-650c184e0bb3?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'classic_elegant',
    name: 'Arabella Saint-Claire - Digital Atelier',
    category: 'professional',
    description: 'Luxury editorial portfolio with art-deco accents, atelier storytelling, curated works, and refined contact flow.',
    previewImage: 'https://images.unsplash.com/photo-1472145246862-b24cf25c4a36?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'vibrant_creative',
    name: 'Luna Evergreen - Organic Studio',
    category: 'creative',
    description: 'Nature-inspired portfolio with soft organic forms, grounded earthy palette, and calm storytelling flow.',
    previewImage: 'https://images.unsplash.com/photo-1463320726281-696a485928c7?auto=format&fit=crop&w=1200&q=80',
  },
];

export const PALETTE_PRESETS: PaletteMeta[] = [
  { id: 'monochrome', name: 'Monochrome', primary: '#000000', secondary: '#444444', accent: '#808080', background: '#FFFFFF', text: '#1A1A1A' },
  { id: 'ocean_blue', name: 'Ocean Blue', primary: '#115D88', secondary: '#1D89A8', accent: '#22B3D0', background: '#F5FBFF', text: '#111827' },
  { id: 'forest_green', name: 'Forest Green', primary: '#1E5631', secondary: '#2C7A4A', accent: '#5AC49B', background: '#F3FBF7', text: '#0F172A' },
  { id: 'warm_earth', name: 'Warm Earth', primary: '#A85B00', secondary: '#C86A3B', accent: '#D8AA78', background: '#FFF8F2', text: '#2A1A12' },
  { id: 'royal_elegance', name: 'Royal Elegance', primary: '#1E2A8A', secondary: '#3D4DB7', accent: '#6675D9', background: '#F4F7FF', text: '#111827' },
  { id: 'sunset_warm', name: 'Sunset Warm', primary: '#D9480F', secondary: '#F97316', accent: '#FB923C', background: '#FFF7ED', text: '#2B1308' },
  { id: 'modern_dark', name: 'Modern Dark', primary: '#2F2F32', secondary: '#4A4A4F', accent: '#13B5BE', background: '#0E0E10', text: '#E5E7EB' },
  { id: 'soft_pastel', name: 'Soft Pastel', primary: '#7A6DB0', secondary: '#9487C3', accent: '#C4B7E6', background: '#FBFAFF', text: '#252329' },
  { id: 'industrial_grey', name: 'Industrial Grey', primary: '#334155', secondary: '#64748B', accent: '#94A3B8', background: '#F8FAFC', text: '#111827' },
  { id: 'crimson_bold', name: 'Crimson Bold', primary: '#B00020', secondary: '#D61F45', accent: '#F0044F', background: '#FFF5F7', text: '#1F0A12' },
];

export const TYPOGRAPHY_PRESETS: TypographyMeta[] = [
  { id: 'modern_sans', name: 'Modern Sans', heading: 'Inter', body: 'Inter', button: 'Inter' },
  { id: 'elegant_serif', name: 'Elegant Serif', heading: 'Playfair Display', body: 'Lora', button: 'Inter' },
  { id: 'tech_mono', name: 'Tech Mono', heading: 'JetBrains Mono', body: 'IBM Plex Sans', button: 'JetBrains Mono' },
  { id: 'creative_mix', name: 'Creative Mix', heading: 'Montserrat', body: 'Open Sans', button: 'Montserrat' },
  { id: 'bold_display', name: 'Bold Display', heading: 'Bebas Neue', body: 'Roboto', button: 'Roboto' },
  { id: 'professional_classic', name: 'Professional Classic', heading: 'Poppins', body: 'Open Sans', button: 'Open Sans' },
];

export const DEFAULT_BUILDER_STATE: PortfolioBuilderState = {
  templateId: 'creative_bold',
  category: 'creative',
  paletteId: 'monochrome',
  palette: PALETTE_PRESETS[0],
  typographyId: 'modern_sans',
  typography: TYPOGRAPHY_PRESETS[0],
  content: {
    fullName: 'Alex Rivera',
    professionalTitle: 'Creative Developer & Designer',
    heroLabel: 'Creative Developer & Designer',
    heroHeadline: 'Building Digital Experiences',
    heroSubheadline:
      'I craft beautiful, functional, and user-centered digital experiences. With 8+ years of expertise in design and development, I bring ideas to life through innovative solutions.',
    bio: 'I craft beautiful, functional, and user-centered digital experiences.',
    aboutTitle: 'Turning Vision Into Reality',
    aboutBody:
      "I'm a passionate creative developer and designer based in San Francisco, specializing in building exceptional digital experiences.\n\nMy journey in tech started over 8 years ago, and since then I've worked with startups, agencies, and Fortune 500 companies.\n\nWhen I'm not coding or designing, I explore new technologies, contribute to open source, and mentor aspiring developers.",
    availability: 'Available for freelance and consulting projects',
    yearsExperience: '8+',
    email: 'alex.rivera@example.com',
    phone: '+1 (555) 123-4567',
    location: 'San Francisco, CA',
    profileImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    heroImageUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=1200&q=80',
    stats: [
      { id: 'st-1', label: 'Years Experience', value: '8+' },
      { id: 'st-2', label: 'Projects Completed', value: '150+' },
      { id: 'st-3', label: 'Happy Clients', value: '50+' },
      { id: 'st-4', label: 'Awards Won', value: '15' },
    ],
    services: [
      { id: 'sv-1', title: 'UI/UX Design', description: 'Creating intuitive and beautiful user interfaces with a focus on user experience and accessibility.', tags: 'Figma, Adobe XD, Sketch, Prototyping' },
      { id: 'sv-2', title: 'Frontend Development', description: 'Building responsive and performant web applications using modern frameworks and best practices.', tags: 'React, Vue.js, Next.js, TypeScript' },
      { id: 'sv-3', title: 'Backend Development', description: 'Designing and implementing scalable server-side solutions and RESTful APIs.', tags: 'Node.js, Python, PostgreSQL, MongoDB' },
      { id: 'sv-4', title: 'Mobile Development', description: 'Creating native and cross-platform mobile applications for iOS and Android.', tags: 'React Native, Flutter, Swift, Kotlin' },
      { id: 'sv-5', title: 'Cloud & DevOps', description: 'Deploying and managing applications on cloud platforms with CI/CD pipelines.', tags: 'AWS, Docker, Kubernetes, GitHub Actions' },
      { id: 'sv-6', title: 'Product Strategy', description: 'Helping businesses define product vision and execute successful digital strategies.', tags: 'Product Design, User Research, Analytics, Agile' },
    ],
    skills: [
      { id: 'sk-1', name: 'UI/UX Design', level: 90 },
      { id: 'sk-2', name: 'React Development', level: 85 },
      { id: 'sk-3', name: 'Brand Strategy', level: 80 },
    ],
    projects: [
      {
        id: 'pr-1',
        title: 'E-Commerce Platform',
        category: 'Web Application',
        client: 'TechStart Commerce',
        year: '2024',
        outcome: 'Launched full-stack commerce workflow with analytics and real-time inventory.',
        link: '#',
        description: 'A full-stack e-commerce solution with real-time inventory management, payment processing, and advanced analytics dashboard.',
        imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=600&q=80',
        tags: 'React, Node.js, MongoDB, Stripe',
      },
      {
        id: 'pr-2',
        title: 'Fitness Tracking App',
        category: 'Mobile App',
        client: 'HealthFlow',
        year: '2024',
        outcome: 'Cross-platform launch with personalized recommendations and progress insights.',
        link: '#',
        description: 'Cross-platform mobile app for tracking workouts, nutrition, and health metrics with AI-powered recommendations.',
        imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
        tags: 'React Native, Firebase, TensorFlow, Redux',
      },
      {
        id: 'pr-3',
        title: 'Creative Agency Website',
        category: 'Web Design',
        client: 'BrightStudio',
        year: '2023',
        outcome: 'Interactive storytelling site with stronger engagement metrics.',
        link: '#',
        description: 'Modern, interactive portfolio website for a creative agency featuring stunning animations and immersive storytelling.',
        imageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=600&q=80',
        tags: 'Next.js, GSAP, Three.js, Tailwind',
      },
      {
        id: 'pr-4',
        title: 'Project Management Tool',
        category: 'SaaS Platform',
        client: 'TaskGrid',
        year: '2023',
        outcome: 'Improved team collaboration with real-time updates and workflow automation.',
        link: '#',
        description: 'Collaborative project management platform with real-time updates, task automation, and team analytics.',
        imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=600&q=80',
        tags: 'Vue.js, Django, PostgreSQL, WebSocket',
      },
      {
        id: 'pr-5',
        title: 'Analytics Dashboard',
        category: 'Dashboard',
        client: 'DataPulse',
        year: '2022',
        outcome: 'Delivered data visibility and forecasting tools for executive teams.',
        link: '#',
        description: 'Real-time analytics dashboard with data visualization, custom reports, and predictive insights for business intelligence.',
        imageUrl: 'https://images.unsplash.com/photo-1551281044-8b6cb35b3f77?auto=format&fit=crop&w=600&q=80',
        tags: 'React, D3.js, Python, AWS',
      },
      {
        id: 'pr-6',
        title: 'Online Learning Platform',
        category: 'E-Learning',
        client: 'SkillBridge',
        year: '2022',
        outcome: 'Built engaging learning journeys with progress tracking and certifications.',
        link: '#',
        description: 'Interactive e-learning platform with video courses, quizzes, progress tracking, and certification system.',
        imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=600&q=80',
        tags: 'Next.js, Express, MySQL, Cloudflare',
      },
    ],
    experience: [
      {
        id: 'ex-1',
        role: 'Senior Full Stack Developer',
        company: 'TechCorp Solutions',
        period: '2024 - Present',
        location: 'San Francisco, CA',
        employmentType: 'Full-time',
        description: 'Leading the development of enterprise-level applications and mentoring junior developers.',
        achievements: 'Architected microservices infrastructure serving 1M+ users.|Led a team of 8 developers across multiple projects.|Improved performance by 45% through optimization.|Implemented CI/CD pipelines reducing deployment time by 60%.',
        technologies: 'Node.js, React, PostgreSQL, AWS, Docker',
      },
      {
        id: 'ex-2',
        role: 'Lead Frontend Developer',
        company: 'Digital Innovations Inc.',
        period: '2021 - 2024',
        location: 'Remote',
        employmentType: 'Full-time',
        description: 'Spearheaded frontend architecture for multiple high-traffic web applications.',
        achievements: 'Built responsive apps using React and Vue.js.|Established component library across 20+ projects.|Mentored team on modern best practices.|Improved user satisfaction by 35% with UX collaboration.',
        technologies: 'React, Vue.js, TypeScript, Design Systems',
      },
      {
        id: 'ex-3',
        role: 'UI/UX Designer & Developer',
        company: 'Creative Studio Agency',
        period: '2019 - 2021',
        location: 'San Francisco, CA',
        employmentType: 'Agency',
        description: 'Designed and developed engaging digital experiences for diverse clients.',
        achievements: 'Created user-centered web and mobile designs.|Conducted user research and usability testing.|Developed interactive prototypes and design systems.|Collaborated with clients on requirements.',
        technologies: 'Figma, Adobe XD, Webflow, JavaScript',
      },
      {
        id: 'ex-4',
        role: 'Junior Web Developer',
        company: 'StartUp Ventures',
        period: '2017 - 2019',
        location: 'San Francisco, CA',
        employmentType: 'Full-time',
        description: 'Started professional journey building websites and learning production workflows.',
        achievements: 'Developed responsive sites using HTML, CSS, and JavaScript.|Contributed to client projects and internal tools.|Participated in code reviews and agile ceremonies.',
        technologies: 'HTML, CSS, JavaScript, Git',
      },
    ],
    education: [
      {
        id: 'ed-1',
        degree: 'B.Sc. Computer Science',
        institution: 'University of California',
        period: '2015 - 2019',
        details: 'Focus on HCI and software engineering. Capstone in user-centered product development.',
      },
    ],
    testimonials: [
      {
        id: 'ts-1',
        name: 'John Davis',
        role: 'CEO',
        company: 'TechStart Inc.',
        quote: 'Alex transformed our vision into reality. The attention to detail and technical expertise was outstanding.',
      },
      {
        id: 'ts-2',
        name: 'Sarah Martinez',
        role: 'Founder',
        company: 'Creative Labs',
        quote: 'Working with Alex was a game-changer for our business. The creative solutions and seamless execution made our project a huge success.',
      },
      {
        id: 'ts-3',
        name: 'Michael Johnson',
        role: 'Product Manager',
        company: 'DataFlow',
        quote: 'Exceptional work. Alex delivered a beautiful, functional product that our users love.',
      },
    ],
    contactTitle: 'Ready to start your next project?',
    contactDescription: "I'm always interested in hearing about new projects and opportunities. Whether you have a question or just want to say hi, feel free to reach out.",
    contactFormTitle: 'Project inquiry form',
    contactFormEnabled: true,
    contactFormSuccessMessage: "Thanks for your message. I'll get back to you soon.",
    primaryCtaLabel: 'View Projects',
    primaryCtaUrl: '#projects',
    secondaryCtaLabel: 'Get In Touch',
    secondaryCtaUrl: '#contact',
    footerText: 'All rights reserved.',
  },
  socials: {
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    twitter: 'https://twitter.com',
    dribbble: 'https://dribbble.com',
    behance: 'https://behance.net',
    instagram: 'https://instagram.com',
    facebook: 'https://facebook.com',
    youtube: '',
  },
  links: [
    { id: 'ln-1', label: 'Newsletter', url: 'https://example.com/newsletter' },
    { id: 'ln-2', label: 'Upgrade', url: 'https://example.com/upgrade' },
    { id: 'ln-3', label: 'Archive', url: 'https://example.com/archive' },
    { id: 'ln-4', label: 'Recommendations', url: 'https://example.com/recommendations' },
  ],
};
